# Build and check LPub3D Snap
# Trevor SANDY <trevor.sandy@gmail.com>
# Last Update: September 27, 2025
# Copyright (C) 2021 - 2025 by Trevor SANDY
#
name: lpub3d
adopt-info: lpub3d
version: v2.4.10
license: GPL-3.0
icon: snap/gui/lpub3d.png

summary: LDraw™ editor for LEGO® style digital building instructions.
description: |
  LPub3D is an Open Source WYSIWYG editing application for creating
  LEGO® style digital building instructions. LPub3D is developed and
  maintained by Trevor SANDY. It uses the LDraw™ parts library, the
  most comprehensive library of digital Open Source LEGO® bricks
  available (www.ldraw.org/ ) and reads the LDraw LDR and MPD model
  file formats. LPub3D is available for free under the GNU Public License v3
  and runs on Windows, Linux and macOS Operating Systems.
  LPub3D is also available as a Linux 'no-install', multi-platform AppImage.
  Portions of LPub3D are based on LPUB© 2007-2009 Kevin Clague,
  LeoCAD© 2025 Leonardo Zide.and additional third party components.
  LEGO® is a trademark of the LEGO Group of companies which does not
  sponsor, authorize or endorse this application.
  © 2015-2025 Trevor SANDY

grade: stable
confinement: strict
base: core24
compression: lzo

platforms:
  amd64:
  arm64:

contact:
  - trevor.sandy@gmail.com
  - https://github.com/trevorsandy
issues:
  - https://github.com/trevorsandy/lpub3d/issues/new/choose
source-code:
  - https://github.com/trevorsandy/lpub3d

apps:
  lpub3d:
    common-id: io.github.trevorsandy.LPub3D
    desktop: usr/share/applications/lpub3d.desktop
    command: usr/bin/lpub3d24
    plugs:
      - home
      - opengl
      - network
    extensions:
      - kde-neon-6

parts:
  ldraw-libraries:
    plugin: nil
    build-environment:
      - STAGE_DIR: ${CRAFT_STAGE}/build_staging
      - LIB_URL: https://github.com/trevorsandy/lpub3d_libs/releases/download/v1.0.1
    build-packages:
      - wget
      - unzip
    override-build: |
      wget --quiet ${LIB_URL}/tenteparts.zip -O tenteparts.zip
      wget --quiet ${LIB_URL}/vexiqparts.zip -O vexiqparts.zip
      wget --quiet ${LIB_URL}/lpub3dldrawunf-25-09-04.zip -O lpub3dldrawunf.zip
      wget --quiet ${LIB_URL}/complete-25-09.zip -O complete.zip
    override-stage: |
      test -d ${STAGE_DIR} || mkdir ${STAGE_DIR}
      test -f ${CRAFT_PART_BUILD}/complete.zip && mv -f ${CRAFT_PART_BUILD}/complete.zip ${STAGE_DIR}/
      test -f ${STAGE_DIR}/complete.zip && echo Official LDraw library staged to ${STAGE_DIR}/complete.zip
      test -f ${CRAFT_PART_BUILD}/lpub3dldrawunf.zip && mv -f ${CRAFT_PART_BUILD}/lpub3dldrawunf.zip ${STAGE_DIR}/
      test -f ${STAGE_DIR}/lpub3dldrawunf.zip && echo Unofficial LDraw library staged to ${STAGE_DIR}/lpub3dldrawunf.zip
      test -f ${CRAFT_PART_BUILD}/vexiqparts.zip && mv -f ${CRAFT_PART_BUILD}/vexiqparts.zip ${STAGE_DIR}/
      test -f ${STAGE_DIR}/vexiqparts.zip && echo VEX LDraw library staged to ${STAGE_DIR}/vexiqparts.zip
      test -f ${CRAFT_PART_BUILD}/tenteparts.zip && mv -f ${CRAFT_PART_BUILD}/tenteparts.zip ${STAGE_DIR}/
      test -f ${STAGE_DIR}/tenteparts.zip && echo TENTE LDraw library staged to ${STAGE_DIR}/tenteparts.zip
      test -f ${STAGE_DIR}/complete.zip && unzip -od ${STAGE_DIR}/ -q ${STAGE_DIR}/complete.zip
      test -f ${STAGE_DIR}/ldraw/complete.zip || ln -s ${STAGE_DIR}/complete.zip ${STAGE_DIR}/ldraw/complete.zip
      test -f ${STAGE_DIR}/ldraw/lpub3dldrawunf.zip || ln -s ${STAGE_DIR}/lpub3dldrawunf.zip ${STAGE_DIR}/ldraw/lpub3dldrawunf.zip
      test -f ${STAGE_DIR}/ldraw/complete.zip && echo LDraw library and archives extracted to ${STAGE_DIR}/ldraw. || true

  source-and-renderers:
    after: [ldraw-libraries]
    plugin: nil
    source: https://github.com/trevorsandy/lpub3d-ci.git
    source-commit: 47dcd485f9f49d976082a3508e7695fb2be83121
    build-environment:
      - LP3D_QT_BIN: /snap/kde-qt6-core24-sdk/current/usr/bin/qt6
      - WORK_DIR: $(realpath ${CRAFT_PART_BUILD}/../build_staging)
      - STAGE_DIR: ${CRAFT_STAGE}/build_staging
      - EXTRAS_DIR: ${STAGE_DIR}/lpub3d/mainApp/extras
      - LDRAWDIR: ${STAGE_DIR}/ldraw
      - LP3D_NO_LDVIEW_CHECK: 'true'
      - LP3D_3RD_DIST_DIR: build_staging
      - LP3D_BUILD_OS: snap
      - LP3D_NO_DEPS: 'true'
      - PLATFORM_CODE: ubu
      - LDGLITE: ldglite-1.3
      - LDVIEW: ldview-4.6
      - POVRAY: lpub3d_trace_cui-3.8
      - LPUB3D: ${PWD##*/}
      - WD: $(cd ../ && echo $PWD)
    build-packages:
      - apt-utils
      - autoconf
      - autotools-dev
      - build-essential
      - ccache
      - curl
      - freeglut3-dev
      - libboost-all-dev
      - libgl2ps-dev
      - libjpeg-dev
      - libopenexr-dev
      - libosmesa6-dev
      - libpng-dev
      - libsdl2-dev
      - libtiff-dev
      - libtinyxml-dev
      - libminizip-dev
      - libtool
      - pkg-config
      - unzip
      - wget
      - zip
      - zlib1g-dev
    stage-packages:
      - libglut3.12
      - libgl2ps1.4
      - libjpeg-turbo8
      - libopenexr-3-1-30
      - libosmesa6
      - libpng16-16t64
      - libsdl2-2.0-0
      - libtiff6
      - libtinyxml2.6.2v5
      - libminizip1t64
      - zlib1g
    override-pull: |
      craftctl default
      test -f builds/utilities/update-config-files.sh && chmod a+x builds/utilities/update-config-files.sh && env OBS=false LPUB3D=lpub3d-ci ./builds/utilities/update-config-files.sh mainApp || :
      test -d ${STAGE_DIR}/lpub3d || mkdir -p ${STAGE_DIR}/lpub3d
      test -d ${STAGE_DIR}/lpub3d && shopt -s dotglob && cp -rf ${CRAFT_PART_SRC}/* ${STAGE_DIR}/lpub3d
      test -d ${STAGE_DIR}/lpub3d/mainApp && echo LPub3D source staged to ${STAGE_DIR}/lpub3d
    override-build: |
      test -d ${WORK_DIR} || mkdir -p ${WORK_DIR}
      test -f ${WORK_DIR}/complete.zip || ln -s ${STAGE_DIR}/complete.zip ${WORK_DIR}/complete.zip
      test -f ${WORK_DIR}/lpub3dldrawunf.zip || ln -s ${STAGE_DIR}/lpub3dldrawunf.zip ${WORK_DIR}/lpub3dldrawunf.zip
      test -f ${LP3D_QT_BIN}/qmake6 && sed -i "s/export QT_SELECT=.*/export QT_SELECT=qt6/g" builds/utilities/CreateRenderers.sh || :
      test -f builds/utilities/CreateRenderers.sh && chmod a+x builds/utilities/CreateRenderers.sh && ./builds/utilities/CreateRenderers.sh || false
    override-stage: |
      test -d ${STAGE_DIR} || mkdir -p ${STAGE_DIR}
      rm -rf ${STAGE_DIR}/${LDGLITE}; mv -f ${WORK_DIR}/${LDGLITE} ${STAGE_DIR}/
      test -d ${STAGE_DIR}/${LDGLITE} && echo LDGLite renderer staged to ${STAGE_DIR}/
      rm -rf ${STAGE_DIR}/${LDVIEW}; mv -f ${WORK_DIR}/${LDVIEW} ${STAGE_DIR}/
      test -d ${STAGE_DIR}/${LDVIEW} && echo LDView renderer staged to ${STAGE_DIR}/
      rm -rf ${STAGE_DIR}/${POVRAY}; mv -f ${WORK_DIR}/${POVRAY} ${STAGE_DIR}/
      test -d ${STAGE_DIR}/${POVRAY} && echo POV-Ray renderer staged to ${STAGE_DIR}/ || true
      test -f ${EXTRAS_DIR}/complete.zip || cp -f ${STAGE_DIR}/complete.zip ${EXTRAS_DIR}/complete.zip
      test -f ${EXTRAS_DIR}/complete.zip && echo LDraw library complete.zip copied to ${EXTRAS_DIR} || true
      test -f ${EXTRAS_DIR}/lpub3dldrawunf.zip || cp -f ${STAGE_DIR}/lpub3dldrawunf.zip ${EXTRAS_DIR}/lpub3dldrawunf.zip
      test -f ${EXTRAS_DIR}/lpub3dldrawunf.zip && echo LDraw library lpub3dldrawunf.zip copied to ${EXTRAS_DIR} || true
      test -f ${EXTRAS_DIR}/tenteparts.zip || cp -f ${STAGE_DIR}/tenteparts.zip ${EXTRAS_DIR}/tenteparts.zip
      test -f ${EXTRAS_DIR}/tenteparts.zip && echo LDraw library tenteparts.zip copied to ${EXTRAS_DIR} || true
      test -f ${EXTRAS_DIR}/vexiqparts.zip || cp -f ${STAGE_DIR}/vexiqparts.zip ${EXTRAS_DIR}/vexiqparts.zip
      test -f ${EXTRAS_DIR}/vexiqparts.zip && echo LDraw library vexiqparts.zip copied to ${EXTRAS_DIR} || true
    override-prime: |
      echo Renderers are not primed. Nothing to do.

  lpub3d:
    after: [source-and-renderers]
    plugin: nil
    source: ${CRAFT_STAGE}/build_staging/lpub3d
    source-type: local
    parse-info: [usr/share/metainfo/lpub3d.appdata.xml]
    build-environment:
      - LP3D_APP: lpub3d-ci
      - LP3D_QT_BIN: /snap/kde-qt6-core24-sdk/current/usr/bin/qt6
      - LP3D_DIST_DIR_PATH: ${CRAFT_STAGE}/build_staging
      - LP3D_PREFIX: ${CRAFT_PART_INSTALL}/usr
      - LP3D_CFLAGS: QMAKE_CFLAGS+=-isystem ${LP3D_PREFIX}/include
      - LP3D_CXXFLAGS: QMAKE_CXXFLAGS+=-isystem ${LP3D_PREFIX}/include
      - LP3D_LFLAGS: QMAKE_LFLAGS+=-L${LP3D_PREFIX}/lib -L${LP3D_PREFIX}/lib/`uname -m`-linux-gnu
      - LDRAWDIR: ${LP3D_DIST_DIR_PATH}/ldraw
      - CPU_CORES: $(nproc)
      - QT_SELECT: qt6
    build-packages:
      - zlib1g-dev
    stage-packages:
      - libglut3.12
      - libasound2t64
      - libasyncns0
      - libboost-system1.83.0
      - libboost-thread1.83.0
      - libflac12t64
      - libgl2ps1.4
      - libglu1-mesa
      - libjbig0
      - libogg0
      - libopenexr-3-1-30
      - libosmesa6
      - libpng16-16t64
      - libpulse0
      - libsdl2-2.0-0
      - libsndfile1
      - libtiff6
      - libtinyxml2.6.2v5
      - libminizip1t64
      - libvorbis0a
      - libvorbisenc2
      - libwayland-cursor0
      - libwayland-egl1
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxss1
    override-build: |
      ${LP3D_QT_BIN}/qmake6 -v
      ${LP3D_QT_BIN}/qmake6 "${LP3D_CFLAGS}" "${LP3D_CXXFLAGS}" "${LP3D_LFLAGS}" PREFIX=${LP3D_PREFIX} CONFIG-=debug_and_release CONFIG+=release CONFIG+=snp
      make -j${CPU_CORES}
      make install

  build-check:
    after: [lpub3d]
    plugin: nil
    build-environment:
      - LDRAWDIR: ${CRAFT_STAGE}/build_staging/ldraw
      - SOURCE_DIR: ${CRAFT_STAGE}/build_staging/lpub3d
      - LP3D_BUILD_OS: snap
      - LP3D_CHECK_LDD: enabled
      - LP3D_INSTALL: /build/lpub3d/parts/lpub3d/install/usr/bin
      - LPUB3D_EXE: ${LP3D_INSTALL}/lpub3d24
      - LDGLITE_EXE: ${LP3D_INSTALL}/lpub3d/3rdParty/ldglite-1.3/bin/ldglite
      - LDVIEW_EXE: ${LP3D_INSTALL}/lpub3d/3rdParty/ldview-4.6/bin/ldview
      - POVRAY_EXE: ${LP3D_INSTALL}/lpub3d/3rdParty/lpub3d_trace_cui-3.8/bin/lpub3d_trace_cui
      - QT_DEBUG_PLUGINS: 1
      - QT_QPA_PLATFORM: wayland
      - QT_QPA_PLATFORM_PLUGIN_PATH: /snap/kde-qt6-core24-sdk/current/usr/lib/`uname -m`-linux-gnu/qt6/plugins
      - QT_PLUGIN_PATH: /snap/kde-qt6-core24-sdk/current/usr/lib/`uname -m`-linux-gnu/qt6/plugins
    build-packages: [xvfb]
    override-build: |
      cd ${SOURCE_DIR} && chmod a+x builds/check/build_checks.sh && ./builds/check/build_checks.sh
    override-prime: |
      echo Build check is not primed. Nothing to do.
